DROP DATABASE IF EXISTS SampleECommerceDb

CREATE DATABASE SampleECommerceDb

CREATE TABLE Users (
    Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    UserName NVARCHAR(50) NOT NULL,
    EncryptedPassword VARBINARY(128) NOT NULL,
    Salt VARBINARY(16) NOT NULL,

    CONSTRAINT AK_UserNameId UNIQUE(UserName)
)

CREATE TABLE UserBalances (
    UserId INT NOT NULL PRIMARY KEY,
    Balance SMALLMONEY NOT NULL DEFAULT (100.00)

    FOREIGN KEY UserId REFERENCES Users(Id)
)

GO
