DROP DATABASE IF EXISTS SampleECommerceDb

CREATE DATABASE SampleECommerceDb

CREATE TABLE Users (
    Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    UserName NVARCHAR(50) NOT NULL,
    EncryptedPassword VARBINARY(128) NOT NULL,
    Salt VARBINARY(16) NOT NULL,
    Balance SMALLMONEY NOT NULL DEFAULT (100.00)

    CONSTRAINT AK_UserNameId UNIQUE(UserName)
)

GO
